# Prompt: GitHub Actions workflow for optimized microservices CI build
name: Optimized Microservice CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: [auth, orders, payments]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install and Test ${{ matrix.service }}
        run: |
          cd services/${{ matrix.service }}
          npm install
          npm run test
