# Prompt: Create a GitHub Actions workflow to run OWASP ZAP nightly on a staging environment and store the HTML report as an artifact.

name: ZAP Nightly Security Scan

on:
  schedule:
    - cron: '0 2 * * *'  # Runs at 2 AM UTC every day
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    steps:
      - name: Start ZAP Scan
        run: |
          docker pull owasp/zap2docker-stable
          docker run -v $(pwd):/zap/wrk/:rw -t owasp/zap2docker-stable             zap-full-scan.py -t https://staging.example.com -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-html-report
          path: zap_report.html
